version: '3'

services:

  couchdb:
    image: couchdb
    container_name: couchdb
    env_file:
      - ./couchdb/couchdb_variables.env
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    ports:
      - "5984:5984"
    networks:
      - third

  models:
    build: ./models
    container_name: models
    volumes:
      - ./models:/home/node/app/src
    ports:
      - "8002:8000"
    depends_on:
      - couchdb
    networks:
      - second
      - third
    command: npm start 

  exp:
    build: ./exp
    container_name: exp
    volumes:
      - ./exp:/home/node/app/src
    ports:
      - "8001:8000"
    depends_on:
      - models
    networks:
      - first
      - second 
    command: npm start 

  web:
    build: ./web
    container_name: web
    volumes:
      - ./web:/home/node/app/src
    ports:
      - "8000:8000"
    depends_on:
      - exp
    networks:
      - first 
    command: npm start 


networks:
  first:
  second:
  third:
